import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join, posix } from "node:path";
import type { ScanResult } from "./types.js";

export const HARD_SKIPS = new Set([
  ".git",
  "node_modules",
  "vendor",
  "target",
  "dist",
  ".autogenerated",
  // Output of `tdk project`: never a source of services.
  ".tdk",
  "shared-platform-engineering",
]);
export const MAX_DEPTH = 8;
export const MAX_FILES = 5000;

interface IgnoreRule {
  base: string;
  regex: RegExp;
  anchored: boolean;
  dirOnly: boolean;
}

function globToRegex(glob: string): string {
  let out = "";
  for (let i = 0; i < glob.length; i++) {
    const c = glob[i] as string;
    if (c === "*" && glob[i + 1] === "*") {
      if (glob[i + 2] === "/") {
        out += "(?:.*/)?";
        i += 2;
      } else {
        out += ".*";
        i += 1;
      }
    } else if (c === "*") out += "[^/]*";
    else if (c === "?") out += "[^/]";
    else out += c.replace(/[.+^${}()|[\]\\]/g, "\\$&");
  }
  return out;
}

function readIgnoreRules(absDir: string, base: string, notes: string[]): IgnoreRule[] {
  let text: string;
  try {
    text = readFileSync(join(absDir, ".gitignore"), "utf8");
  } catch {
    return [];
  }
  const rules: IgnoreRule[] = [];
  for (const raw of text.split(/\r?\n/)) {
    let pattern = raw.trim();
    if (!pattern || pattern.startsWith("#")) continue;
    if (pattern.startsWith("!")) {
      notes.push(`${posix.join(base, ".gitignore")}: negation (${pattern}) is not supported`);
      continue;
    }
    const dirOnly = pattern.endsWith("/");
    if (dirOnly) pattern = pattern.slice(0, -1);
    const anchored = pattern.includes("/");
    if (pattern.startsWith("/")) pattern = pattern.slice(1);
    rules.push({ base, regex: new RegExp(`^${globToRegex(pattern)}$`), anchored, dirOnly });
  }
  return rules;
}

function isIgnored(rules: IgnoreRule[], rel: string, name: string, isDir: boolean): boolean {
  return rules.some((rule) => {
    if (rule.dirOnly && !isDir) return false;
    const underBase = rule.base === "" ? rel : rel.slice(rule.base.length + 1);
    if (rule.base !== "" && !rel.startsWith(`${rule.base}/`)) return false;
    return rule.regex.test(rule.anchored ? underBase : name);
  });
}

/**
 * Lists the files under `root` that detectors may claim. Skips build and dependency
 * directories and `.gitignore`d paths, never follows symlinks, and caps depth and file count.
 */
export function scanTree(
  root: string,
  limits = { depth: MAX_DEPTH, files: MAX_FILES },
): ScanResult {
  const files: string[] = [];
  const notes: string[] = [];
  const managed: string[] = [];
  let depthCapped = false;
  let fileCapped = false;

  // In a TDK project, `services/` holds manifests and generated compose files, not sources.
  const isTdkProject = existsSync(join(root, ".tdk", "project.json"));
  if (isTdkProject) notes.push("TDK project detected: services/ was not scanned");

  const walk = (rel: string, depth: number, inherited: IgnoreRule[]) => {
    const abs = join(root, rel);
    const rules = [...inherited, ...readIgnoreRules(abs, rel, notes)];
    const entries = readdirSync(abs, { withFileTypes: true }).sort((a, b) =>
      a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
    );
    // A directory with a service.json is already a TDK service (possibly written by an earlier
    // import, with a scaffolded Dockerfile): re-importing it would not be idempotent.
    if (rel !== "" && entries.some((e) => e.isFile() && e.name === "service.json")) {
      managed.push(rel);
      return;
    }
    for (const entry of entries) {
      if (fileCapped) return;
      if (entry.isSymbolicLink()) continue;
      const entryRel = rel === "" ? entry.name : `${rel}/${entry.name}`;
      if (entry.isDirectory()) {
        if (HARD_SKIPS.has(entry.name) || isIgnored(rules, entryRel, entry.name, true)) continue;
        if (isTdkProject && entryRel === "services") continue;
        if (depth >= limits.depth) {
          depthCapped = true;
          continue;
        }
        walk(entryRel, depth + 1, rules);
      } else if (entry.isFile()) {
        if (isIgnored(rules, entryRel, entry.name, false)) continue;
        if (files.length >= limits.files) {
          fileCapped = true;
          return;
        }
        files.push(entryRel);
      }
    }
  };

  walk("", 0, []);
  if (managed.length) {
    notes.push(
      `${managed.length} director${managed.length === 1 ? "y" : "ies"} with a service.json skipped (already TDK services)`,
    );
  }
  if (depthCapped) notes.push(`directories deeper than ${limits.depth} levels were not scanned`);
  if (fileCapped) notes.push(`stopped after ${limits.files} files; later files were not scanned`);
  return { files: files.sort(), notes };
}
